CmampTask11789: delete ssh update pythonpath

diff --git a/.github/workflows/common_run_tests.yml b/.github/workflows/common_run_tests.yml
--- a/.github/workflows/common_run_tests.yml
+++ b/.github/workflows/common_run_tests.yml
@@ -6,15 +6,6 @@ on:
             description: 'Name of the test to run. Example: run_fast_tests.'
             required: true
             type: string
-          enable-ssh:
-            description: 'Run ssh step'
-            required: false
-            type: string
-        secrets:
-          CALLER_GITHUB_TOKEN:
-            required: false
-          CALLER_GITHUB_TOKEN2:
-            required: false
 env:
   CSFY_CI: true
   # CSFY_ECR_BASE_PATH: ${{ vars.CSFY_ECR_BASE_PATH }}
@@ -75,7 +66,21 @@ jobs:
       # To see the modules in `amp` and `helpers_root`, PYTHONPATH needs to
       # include them in the same way we do in `setenv.sh`.
       - name: Update PYTHONPATH
-        run: echo "PYTHONPATH=.:helpers_root:amp" >> $GITHUB_ENV
+        run: | 
+          PYTHONPATH="$(realpath $START_DIR)"
+          # Move into root to properly resolve submodules.
+          cd "$START_DIR" || { echo "❌ Failed to change directory to $START_DIR"; exit 1; }
+          # Add all submodule paths (recursively).
+          SUBMODULES_PATHS=$(git submodule foreach --quiet --recursive 'echo $(pwd)' | paste -sd:)
+          PYTHONPATH="$PYTHONPATH:$SUBMODULES_PATHS"
+          # Export and show final PYTHONPATH.
+          echo "PYTHONPATH=$PYTHONPATH"
+          echo "PYTHONPATH=$PYTHONPATH" >> $GITHUB_ENV
+
+      # # To see the modules in `amp` and `helpers_root`, PYTHONPATH needs to
+      # # include them in the same way we do in `setenv.sh`.
+      # - name: Update PYTHONPATH
+      #   run: echo "PYTHONPATH=.:helpers_root:amp" >> $GITHUB_ENV
 
       # Install packages that are required to run the job via GH.
       - name: Install dependencies
@@ -92,20 +97,6 @@ jobs:
       # cost saving purposes to run the regressions on.
       - name: Pull image from GHCR
         run: invoke docker_pull
-
-      - name: ssh
-        if: ${{ inputs.enable-ssh == 'enable' }}
-        uses: lhotari/action-upterm@v1
-        env:
-          ${{ insert }}: ${{ secrets }}          
-          # CSFY_AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
-          # CSFY_AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
-          # CSFY_AWS_SESSION_TOKEN: ${{ env.AWS_SESSION_TOKEN }}
-          # CSFY_AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}
-          # CSFY_AWS_S3_BUCKET: ${{ vars.CSFY_AWS_S3_BUCKET }}
-          # GH_ACTION_ACCESS_TOKEN: ${{ secrets.CALLER_GITHUB_TOKEN }}
-          # GH2_ACTION_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          # GH3_ACTION_ACCESS_TOKEN: ${{ secrets.GH_ACTION_ACCESS_TOKEN }}
 
       - name: Run tests
         env:
